merged dmenuhandlerXclip into on dmenuhandler script

diff --git a/.local/bin/dmenuhandler b/.local/bin/dmenuhandler
--- a/.local/bin/dmenuhandler
+++ b/.local/bin/dmenuhandler
@@ -1,29 +1,38 @@
 #!/bin/sh
 
-# Feed this script a link and it will give dmenu
+# url this script a link and it will give dmenu
 # some choice programs to use to open it.
-feed="${1:-$(printf "%s" | dmenu -p 'Paste URL or file path')}"
-base="$(basename "$feed")"
+url="${1:-$(printf "%s" | dmenu -p 'Paste url or file path')}"
+base="$(basename "$url")"
 
-case "$(printf "Copy URL\\nsxiv\\nsetbg\\nPDF\\nbrowser\\nlynx\\nvim\\nmpv\\nmpv loop\\nmpv float\\nYT\\nYT any quality\\nYTA" | dmenu -i -p "Open it with?")" in #\\nqueue download\\nqueue yt-dl\\nqueue yt-dl audio
-	"Copy URL") echo "$feed" | tr -d '\n' | xclip -selection clipboard ;;
-	mpv) setsid -f mpv -quiet "$feed" >/dev/null 2>&1 ;;
-	"mpv loop") setsid -f mpv -quiet --loop "$feed" >/dev/null 2>&1 ;;
-	"mpv float") setsid -f "$TERMINAL" -e mpv --geometry=+0-0 --autofit=30%  --title="mpvfloat" "$feed" >/dev/null 2>&1 ;;
+case "$(printf "Copy url\\nsxiv\\nsetbg\\nPDF\\nbrowser\\nlynx\\nvim\\nmpv\\nmpvAudio\\nmpv float\\nYT\\nYTA\\nYT any quality\\nHtml\\nariaAdd\\nariaDownload" | dmenu -i -p "Open it with?")" in #\\nqueue download\\nqueue yt-dl\\nqueue yt-dl audio
+	"Copy url") echo "$url" | tr -d '\n' | xclip -selection clipboard ;;
+	mpv) setsid -f mpv -quiet "$url" >/dev/null 2>&1 ;;
+	mpvAudio) $TERMINAL -e mpv -quiet --no-video "$url"  ;;
+	# "mpv loop") setsid -f mpv -quiet --loop "$url" >/dev/null 2>&1 ;;
+	# "mpv float") setsid -f "$TERMINAL" -e mpv --geometry=+0-0 --autofit=30%  --title="mpvfloat" "$url" >/dev/null 2>&1 ;;
+	"mpv float") setsid -f mpv --geometry=+0-0 --autofit=30%  --title="mpvfloat" "$url" >/dev/null 2>&1 ;;
 	"YT")  notify-send "🎥 downloading "$base""
-	       setsid -f yt-dlp --external-downloader aria2c -f 22 -P "$XDG_VIDEOS_DIR/yt" "$feed" > /dev/null 2>&1 ;;
+		setsid -f yt-dlp --external-downloader aria2c -f 22 -P "$XDG_VIDEOS_DIR/youtube" "$url" > /dev/null 2>&1 ;;
 	"YT any quality")  notify-send "🎥 downloading "$base""
-	       setsid -f yt-dlp --external-downloader aria2c -P "$XDG_VIDEOS_DIR/youtube" "$feed" > /dev/null 2>&1 ;;
+		setsid -f yt-dlp --external-downloader aria2c -P "$XDG_VIDEOS_DIR/youtube" "$url" > /dev/null 2>&1 ;;
 	"YTA")  notify-send "📢 downloading "$base""
-		setsid -f yt-dlp -f bestaudio/best -P "$XDG_MUSIC_DIR/youtube" --external-downloader aria2c "$feed" > /dev/null 2>&1;;
-	# "Max 720") qndl "$feed" 'yt-dlp -f bestvideo[height<=?720]+bestaudio/best -P $XDG_VIDS_DIR/youtube" --add-metadata -icx' >/dev/null 2>&1 ;;
-	#"queue yt-dl") qndl "$feed" >/dev/null 2>&1 ;;
-	#"queue yt-dl audio") qndl "$feed" 'yt-dlp -f bestaudio/best --add-metadata -icx' >/dev/null 2>&1 ;;
-	#"queue download") qndl "$feed" 'curl -LO' >/dev/null 2>&1 ;;
-	PDF) curl -sL "$feed" > "/tmp/$(echo "$feed" | sed "s/.*\///;s/%20/ /g")" && zathura "/tmp/$(echo "$feed" | sed "s/.*\///;s/%20/ /g")"  >/dev/null 2>&1 ;;
-	sxiv) curl -sL "$feed" > "/tmp/$(echo "$feed" | sed "s/.*\///;s/%20/ /g")" && sxiv -a "/tmp/$(echo "$feed" | sed "s/.*\///;s/%20/ /g")"  >/dev/null 2>&1 ;;
-	vim) curl -sL "$feed" > "/tmp/$(echo "$feed" | sed "s/.*\///;s/%20/ /g")" && setsid -f "$TERMINAL" -e "$EDITOR" "/tmp/$(echo "$feed" | sed "s/.*\///;s/%20/ /g")"  >/dev/null 2>&1 ;;
-	setbg) curl -L "$feed" > $XDG_CACHE_HOME/pic ; xwallpaper --zoom $XDG_CACHE_HOME/pic >/dev/null 2>&1 ;;
-	browser) setsid -f "$BROWSER" "$feed" >/dev/null 2>&1 ;;
-	lynx) lynx "$feed" >/dev/null 2>&1 ;;
+		yt-dlp -f bestaudio/best -P "$XDG_MUSIC_DIR" --external-downloader aria2c "$url" > /dev/null 2>&1;;
+	# "Max 720") qndl "$url" 'yt-dlp -f bestvideo[height<=?720]+bestaudio/best -P $XDG_VIDS_DIR/youtube --add-metadata -icx' >/dev/null 2>&1 ;;
+	#"queue yt-dl") qndl "$url" >/dev/null 2>&1 ;;
+	#"queue yt-dl audio") qndl "$url" 'yt-dlp -f bestaudio/best --add-metadata -icx' >/dev/null 2>&1 ;;
+	#"queue download") qndl "$url" 'curl -LO' >/dev/null 2>&1 ;;
+	PDF) curl -sL "$url" > "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")" && zathura "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")"  >/dev/null 2>&1 ;;
+	sxiv) curl -sL "$url" > "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")" && sxiv -a "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")"  >/dev/null 2>&1 ;;
+	vim) curl -sL "$url" > "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")" && setsid -f "$TERMINAL" -e "$EDITOR" "/tmp/$(echo "$url" | sed "s/.*\///;s/%20/ /g")"  >/dev/null 2>&1 ;;
+	setbg) curl -L "$url" > $XDG_CACHE_HOME/pic ; xwallpaper --zoom $XDG_CACHE_HOME/pic >/dev/null 2>&1 ;;
+	browser) setsid -f "$BROWSER" "$url" >/dev/null 2>&1 ;;
+	lynx) lynx "$url" >/dev/null 2>&1 ;;
+	PDF) wkhtmltopdf "$url" "$XDG_DOCUMENTS_DIR/readlater/$base.pdf"
+	     notify-send "📜 $base.pdf downloaded"  ;;
+	#|| notify-send "❗Exporting $base pdf failed" && exit 1
+	Html) single-file --browser-executable-path /usr/bin/chromium "$url" --output-directory "$XDG_DOCUMENTS_DIR/readlater"
+	      notify-send "📜 $base downloaded" ;;
+	ariaAdd) aria2c -i /tmp/ariaxclip -d "$HOME/.aria2/sequences" "$url" && notify-send -u low 'Sequence Downloaded ✅' && mv /tmp/ariaxclip "$HOME/.aria2/sequences/done.txt" ;;
+	ariaDownload) aria2c -d "$HOME/.aria2/files" "$url" && notify-send -u low 'File Downloaded ✅' ;;
 esac
