Added my/bookmark-set funciton. Much better than the default bookmark-set

diff --git a/.local/bin/misc/dmenumount b/.local/bin/misc/dmenumount
--- a/.local/bin/misc/dmenumount
+++ b/.local/bin/misc/dmenumount
@@ -3,26 +3,36 @@
 # Mounts Android Phones and USB drives (encrypted or not). This script will
 # replace the older `dmenumount` which had extra steps and couldn't handle
 # encrypted drives.
-# TODO: Remove already mounted Android phones from prompt.
-# TODO: Try mount first for drives if in fstab to avoid directory prompt?
+# TODO: Try decrypt for drives in crtypttab
 # TODO: Add some support for connecting iPhones (although they are annoying).
 
-set -e
+IFS='
+'
+# Function for escaping cell-phone names.
+escape(){ echo "$@" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g" ;}
 
 # Check for phones.
 phones="$(simple-mtpfs -l 2>/dev/null | sed "s/^/📱/")"
+mountedphones="$(grep "simple-mtpfs" /etc/mtab)"
+# If there are already mounted phones, remove them from the list of mountables.
+[ -n "$mountedphones" ] && phones="$(for phone in $phones; do
+	for mounted in $mountedphones; do
+		escphone="$(escape "$phone")"
+		[[ "$mounted" =~ "$escphone" ]] && break 1
+	done && continue 1
+	echo "$phone"
+done)"
+
 # Check for drives.
-alldrives="$(lsblk -rpo "uuid,name,type,size,label,mountpoint,fstype")"
+lsblkoutput="$(lsblk -rpo "uuid,name,type,size,label,mountpoint,fstype")"
 # Get all LUKS drives
-allluks="$(echo "$alldrives" | grep crypto_LUKS)" || true
+allluks="$(echo "$lsblkoutput" | grep crypto_LUKS)"
 # Get a list of the LUKS drive UUIDs already decrypted.
 decrypted="$(find /dev/disk/by-id/dm-uuid-CRYPT-LUKS2-* | sed "s|.*LUKS2-||;s|-.*||")"
 # Functioning for formatting drives correctly for dmenu:
 filter() { sed "s/ /:/g" | awk -F':' '$7==""{printf "%s%s (%s) %s\n",$1,$3,$5,$6}' ; }
 
 # Get only LUKS drives that are not decrypted.
-IFS='
-'
 unopenedluks="$(for drive in $allluks; do
 	uuid="${drive%% *}"
 	uuid="${uuid//-}"	# This is a bashism.
@@ -33,12 +43,16 @@ unopenedluks="$(for drive in $allluks; do
 done | filter)"
 
 # Get all normal, non-encrypted or decrypted partitions that are not mounted.
-normalparts="$(echo "$alldrives"| grep -v crypto_LUKS | grep 'part\|rom\|crypt' | sed "s/^/💾 /" | filter )"
+normalparts="$(echo "$lsblkoutput"| grep -v crypto_LUKS | grep 'part\|rom\|crypt' | sed "s/^/💾 /" | filter )"
 
 # Add all to one variable. If no mountable drives found, exit.
 alldrives="$(echo "$phones
 $unopenedluks
 $normalparts" | sed "/^$/d;s/ *$//")"
+
+# Quit the script if a sequential command fails.
+set -e
+
 test -n "$alldrives"
 
 # Feed all found drives to dmenu and get user choice.
@@ -54,12 +68,19 @@ getmount(){
 	fi
 }
 
+attemptmount(){
+		# Attempt to mount without a mountpoint, to see if drive is in fstab.
+		sudo -A mount "$chosen" || return 1
+		notify-send "💾Drive Mounted." "$chosen mounted."
+		exit
+}
+
 case "$chosen" in
 	💾*)
 		chosen="${chosen%% *}"
 		chosen="${chosen:1}"	# This is a bashism.
-		getmount
-		sudo mount "$chosen" "$mp"
+		attemptmount || getmount
+		sudo -A mount "$chosen" "$mp" -o uid="$(id -u)",gid="$(id -g)"
 		notify-send "💾Drive Mounted." "$chosen mounted to $mp."
 		;;
 
@@ -77,17 +98,17 @@ case "$chosen" in
 		# Check if now decrypted.
 		test -b "/dev/mapper/usb$num"
 
-		getmount
-		sudo mount "/dev/mapper/usb$num"  "$mp"
+		attemptmount || getmount
+		sudo -A mount "/dev/mapper/usb$num" "$mp" -o uid="$(id -u)",gid="$(id -g)"
 		notify-send "🔓Decrypted drive Mounted." "$chosen decrypted and mounted to $mp."
 		;;
 
 	📱*)
+		notify-send "❗Note" "Remember to allow file access on your phone now."
 		getmount
-		echo "OK" | dmenu -i -p "Tap Allow on your phone if it asks for permission and then press enter"
-		chosen="${chosen%%:*}"
-		chosen="${chosen:1}"	# This is a bashism.
-		simple-mtpfs --device "$chosen" "$mp"
+		number="${chosen%%:*}"
+		number="${chosen:1}"	# This is a bashism.
+		sudo -A simple-mtpfs -o allow_other -o fsname="simple-mtpfs-$(escape "$chosen")" --device "$number" "$mp"
 		notify-send "🤖 Android Mounted." "Android device mounted to $mp."
 		;;
 esac
