Updated the scripts so they are Wayland/X11 compatible, including menus. Added different updates to the scripts

diff --git a/.local/bin/misc/touchpad_toggle b/.local/bin/misc/touchpad_toggle
--- a/.local/bin/misc/touchpad_toggle
+++ b/.local/bin/misc/touchpad_toggle
@@ -1,20 +1,31 @@
-#!/bin/bash
-
-declare -i ID
-ID=$(xinput list | grep -Eio '(touchpad|glidepoint)\s*id=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}')
+#!/usr/bin/env bash
 
 case "$1" in
     "on")
-        xinput enable "$ID"
-        # echo "Touchpad enabled."
-        # notify-send -u low 'Touchpad' 'Touchpad Enabled'
+        if [[ -n $WAYLAND_DISPLAY ]]; then
+            ID="$(swaymsg -t get_inputs | jq -r '.[] | select(.type | test("touchpad"; "i")) | .identifier')"
+            swaymsg input "$ID" events enabled
+        elif [[ -n $DISPLAY ]]; then
+            ID=$(xinput list | grep -Eio '(touchpad|glidepoint)\s*id=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}')
+            xinput enable "$ID"
+        else
+            echo "Error: No Wayland or X11 display detected" >&2
+            exit 1
+        fi
         ;;
     "off")
-        xinput disable "$ID"
-        # echo "Touchpad disabled."
-        # notify-send -u low 'Touchpad' 'Touchpad Disabled'
+        if [[ -n $WAYLAND_DISPLAY ]]; then
+            ID="$(swaymsg -t get_inputs | jq -r '.[] | select(.type | test("touchpad"; "i")) | .identifier')"
+            swaymsg input "$ID" events disabled
+        elif [[ -n $DISPLAY ]]; then
+            ID=$(xinput list | grep -Eio '(touchpad|glidepoint)\s*id=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}')
+            xinput disable "$ID"
+        else
+            echo "Error: No Wayland or X11 display detected" >&2
+            exit 1
+        fi
         ;;
     *)
-    exit 1
-    ;;
+        exit 1
+        ;;
 esac
diff --git a/.local/bin/misc/yt-thumbnails-downloader b/.local/bin/misc/yt-thumbnails-downloader
--- a/.local/bin/misc/yt-thumbnails-downloader
+++ b/.local/bin/misc/yt-thumbnails-downloader
@@ -1,10 +1,25 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-for file in "$@"; do
-    filename=$(basename "$file")
+# Function that will be run in each thread
+process_item() {
+    local file="$1"
+    local filename=$(basename "$file")
+    local title
+
     youtube-dl --match-filter "!short"  --write-thumbnail -o "%(title)s.%(ext)s" --convert-thumbnail jpg --skip-download "ytsearch:${filename%.*}" -P "$HOME/.cache/yt-audio-thumbnails/"
     title="$(youtube-dl --match-filter "!short" --get-title -o "%(title)s.%(ext)s" --skip-download "ytsearch:${filename%.*}")"
-    extension="${file##*.}"
-    newtitle="$title.$extension"
-    [ ! -f "newtitle" ] && mv "$file" "$newtitle"
-done
+    local extension="${file##*.}"
+    local newtitle="$title.$extension"
+
+    [ ! -f "$newtitle" ] && mv "$file" "$newtitle"
+}
+
+# Number of threads to run in parallel
+num_threads=10
+
+# Check if GNU Parallel is installed
+command -v parallel >/dev/null 2>&1 || { echo >&2 "GNU Parallel is required but not installed. Aborting."; exit 1; }
+
+# Run the process_item function in parallel for each input file
+export -f process_item
+parallel -j "$num_threads" process_item ::: "$@"
